apiVersion: batch/v1
kind: Job
metadata:
  name: init-mysql
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: init-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_HOST
              value: w8t-mysql
            - name: MYSQL_ROOT_PASSWORD
              value: w8t.123
            - name: MYSQL_DATABASE
              value: watchalert
          volumeMounts:
            - name: sql-volume
              mountPath: /sql
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command: ["sh", "-c", "sh /sql/auto_import.sh"]
      volumes:
        - name: sql-volume
          configMap:
            name: w8t-init-config
      restartPolicy: OnFailure