apiVersion: apps/v1
kind: Deployment
metadata:
  name: w8t-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w8t-redis
  template:
    metadata:
      labels:
        app: w8t-redis
    spec:
      containers:
        - name: w8t-redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          hostPath:
            path: /data/w8t/redis
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: w8t-redis
  namespace: default
spec:
  selector:
    app: w8t-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379